# This is a tutorial/demo on how to use the `Datamart` REST API.

## Installation

This Jupyter notebook requires at least Python 3.3 with these packages installed:

```
pip install notebook
pip install requests
pip install pandas
```

To run change to the directory containing this notebook, and type

```
jupyter notebook
```

Then, open this page in the web browser: http://localhost:8888/notebooks/Datamart%20Data%20API%20Demo.ipynb

## Configuration

By default the this notebook accesses the Datamart REST API server at ISI. Edit the cell below to choose a different server.

To run you own server **locally** follow the instructions here: [README](README.md)

In [1]:
## set datamart api url
# The datamart server running at ISI
# datamart_api_url = 'https://datamart:datamart-api-789@dsbox02.isi.edu:8888/datamart-api-wm'

# Datamart server running on localhost
# datamart_api_url = 'http://localhost:14080'

# Datamart server running on localhost in development mode
datamart_api_url = 'http://localhost:12543'

## Import python modules

In [2]:
from requests import get,post,put,delete
import json
import pandas as pd
from io import StringIO
from IPython.display import display, HTML
import os

In [27]:
def upload_data(file_path, url):
    file_name = os.path.basename(file_path)
    files = {
        'file': (file_name, open(file_path, mode='rb'), 'application/octet-stream')
    }
    response = put(url, files=files)
    if response.status_code == 400:
        print(json.dumps(response.json(), indent=2))
    else:
        print(response.json())

In [3]:
def upload_data_annotated(file_path, url, put_data=True):
    file_name = os.path.basename(file_path)
    files = {
        'file': (file_name, open(file_path, mode='rb'), 'application/octet-stream')
    }
    if put_data:
        response = put(url, files=files)
    else:
        response = post(url, files=files)
    if response.status_code == 400:
        print(json.dumps(response.json(), indent=2))
    else:
        print(json.dumps(response.json(), indent=2))

### Get all datasets

**GET `/metadata/datasets`**

In [4]:
response = get(f'{datamart_api_url}/metadata/datasets')
df = pd.DataFrame(response.json())
df

,name,description,url,dataset_id
0,UAZ Indicators,"Collection of indicators, including indicators...",https://github.com/ml4ai/delphi,UAZ
1,WDI dataset,World Development Indicators,https://databank.worldbank.org/source/world-de...,WDI
2,Corruption Perceptions Index,Transparency International Corruption Percept...,https://www.transparency.org/,TICPI
3,SIPRI Military Expenditure,"Military expenditure by country, in millions o...",https://sipri.org/databases/milex,SIPRI
4,economic fitness dataset,EconomicFitness,https://databank.banquemondiale.org/source/eco...,EconomicFitness
5,Agricultural Market Information System (AMIS),The Agricultural Market Information System (AM...,http://www.amis-outlook.org,AMIS
6,test test test,testy test,https://test.com,TEST000
7,World Press Freedom Index,Published every year since 2002 by Reporters W...,https://rsf.org/en,WPFI
8,Poverty Rate Global DP,Poverty Rate Global DP,http://url,DPPoverty
9,FSI dataset,data downloaded from FSI,https://fragilestatesindex.org,FSI
10,OECD dataset,data downloaded from OECD,https://data.oecd.org,OECD
11,WGI dataset,Worldwide Governance Indicators,https://databank.worldbank.org/source/worldwid...,WGI

As of June 25, 2020 there are 11 datasets in the database. More datasets will be added as they are processed. 

We can also get metadata about one dataset using the `dataset_id`.

### Get metadata about one dataset

**GET `/metadata/datasets/{dataset_id}`**

In [5]:
response = get(f'{datamart_api_url}/metadata/datasets/WDI')
df = pd.DataFrame(response.json())
df

,name,description,url,dataset_id
0,WDI dataset,World Development Indicators,https://databank.worldbank.org/source/world-de...,WDI

### Get all variables in a dataset

**GET `/metadata/datasets/{dataset_id}/variables`**

In [6]:
response = get(f'{datamart_api_url}/metadata/datasets/WDI/variables')
print(json.dumps(response.json()[:5], indent=2)) # print only 5 variables

[
  {
    "name": "_2005 PPP conversion factor, GDP (LCU per international $)",
    "variable_id": "_2005_ppp_conversion_factor_gdp_lcu_per_international",
    "description": "_2005 PPP conversion factor, GDP (LCU per international $) in WDI",
    "corresponds_to_property": "PWDI-002",
    "qualifier": [
      {
        "name": "point in time",
        "identifier": "P585"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      }
    ]
  },
  {
    "name": "_2005 PPP conversion factor, private consumption (LCU per international $)",
    "variable_id": "_2005_ppp_conversion_factor_private_consumption_lcu_per_international",
    "description": "_2005 PPP conversion factor, private consumption (LCU per international $) in WDI",
    "corresponds_to_property": "PWDI-003",
    "qualifier": [
      {
        "name": "point in time",
        "identifier": "P585"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      }
    ]
  },
  {
    "name": "Access to clean fuels and technologies for cooking (% of population)",
    "variable_id": "access_to_clean_fuels_and_technologies_for_cooking_of_population",
    "description": "Access to clean fuels and technologies for cooking (% of population) in WDI",
    "corresponds_to_property": "PWDI-004",
    "qualifier": [
      {
        "name": "point in time",
        "identifier": "P585"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      }
    ]
  },
  {
    "name": "Access to electricity (% of population)",
    "variable_id": "access_to_electricity_of_population",
    "description": "Access to electricity (% of population) in WDI",
    "corresponds_to_property": "PWDI-005",
    "qualifier": [
      {
        "name": "point in time",
        "identifier": "P585"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      }
    ]
  },
  {
    "name": "Access to electricity, rural (% of rural population)",
    "variable_id": "access_to_electricity_rural_of_rural_population",
    "description": "Access to electricity, rural (% of rural population) in WDI",
    "corresponds_to_property": "PWDI-006",
    "qualifier": [
      {
        "name": "point in time",
        "identifier": "P585"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      }
    ]
  }
]

In [7]:
print('Total number of variables in dataset: {} is {}'.format('WDI', len(response.json())))

Total number of variables in dataset: WDI is 1429

### Get metadata about one variable

**GET `/metadata/datasets/{dataset_id}/variables/{variable_id}`**

In [8]:
response = get(f'{datamart_api_url}/metadata/datasets/WDI/variables/access_to_electricity_of_population')
print(json.dumps(response.json(), indent=2))

{
  "name": "Access to electricity (% of population)",
  "variable_id": "access_to_electricity_of_population",
  "dataset_id": "WDI",
  "description": "Access to electricity (% of population) in WDI",
  "corresponds_to_property": "PWDI-005",
  "qualifier": [
    {
      "name": "point in time",
      "identifier": "P585"
    },
    {
      "name": "stated in",
      "identifier": "P248"
    }
  ]
}

### Find a variable using keyword search

**GET `/metadata/variables?keyword={keyword}`**

Query for datasets related to: **road**

In [9]:
response = get(f'{datamart_api_url}/metadata/variables?keyword=road')
df = pd.DataFrame(response.json())
df

,variable_id,name,rank,dataset_id
0,mortality_caused_by_road_traffic_injury_per_10...,Mortality caused by road traffic injury (per ...,0.075991,WDI
1,road_fatalities,Road Fatalities,0.075991,OECD
2,VUAZ-8054,WDI: Mortality caused by road traffic injury[...,0.060793,UAZ

Query datasets related to: **road AND fatalities**

In [10]:
response = get(f'{datamart_api_url}/metadata/variables?keyword=road fatalities')
df = pd.DataFrame(response.json())
df

       variable_id              name      rank dataset_id
0  road_fatalities   Road Fatalities  0.334428       OECD

Query datasets related to: **road OR fatalities**

In [11]:
response = get(f'{datamart_api_url}/metadata/variables?keyword=road&keyword=fatalities')
df = pd.DataFrame(response.json())
df

,variable_id,name,rank,dataset_id
0,road_fatalities,Road Fatalities,0.075991,OECD
1,mortality_caused_by_road_traffic_injury_per_10...,Mortality caused by road traffic injury (per ...,0.037995,WDI
2,VUAZ-8054,WDI: Mortality caused by road traffic injury[...,0.030396,UAZ
3,VUAZ-8136,Conflict fatalities[number of cases],0.030396,UAZ

### Find a variable for a given location

**GET `/metadata/variables?country={keyword}`**

Find variables containing data in a given **country**

In [13]:
response = get(f'{datamart_api_url}/metadata/variables?country=Ethiopia')
df = pd.DataFrame(response.json())
df.head(20)

,variable_id,variable_text,name,dataset_id
0,VUAZ-1,"'bioenergi':2,11 'energi':9 'fao':1 'product':...",FAO: Bioenergy production as a % of total ren...,UAZ
1,VUAZ-9,'agricultur':9 'ch4':3 'emiss':2 'energi':4 'e...,"FAO: Emissions (CH4) (Energy), Transport fuel...",UAZ
2,VUAZ-0,"'agricultur':2,16 'energi':5,11,13 'fao':1 'fo...",FAO: Agriculture and forestry energy use as a...,UAZ
3,VUAZ-2,'agricultur':4 'consumpt':2 'energi':5 'fao':1...,"FAO: Consumption in Agriculture, Energy used ...",UAZ
4,VUAZ-3,'agricultur':4 'consumpt':2 'fao':1 'fisheri':...,"FAO: Consumption in Agriculture, Fuel oil use...",UAZ
5,VUAZ-4,'agricultur':4 'consumpt':2 'diesel':7 'fao':1...,"FAO: Consumption in Agriculture, Gas-diesel o...",UAZ
6,VUAZ-5,"'agricultur':4,9 'consumpt':2 'excl':10 'fao':...","FAO: Consumption in Agriculture, Transport fu...",UAZ
7,VUAZ-6,"'ch4':3 'emiss':2 'energi':4,5 'fao':1 'fisher...","FAO: Emissions (CH4) (Energy), Energy used in...",UAZ
8,VUAZ-7,'ch4':3 'emiss':2 'energi':4 'fao':1 'fisheri'...,"FAO: Emissions (CH4) (Energy), Fuel oil used ...",UAZ
9,VUAZ-8,'ch4':3 'diesel':7 'emiss':2 'energi':4 'fao':...,"FAO: Emissions (CH4) (Energy), Gas-diesel oil...",UAZ
10,VUAZ-10,"'co2':3 'emiss':2 'energi':4,5 'fao':1 'fisher...","FAO: Emissions (CO2) (Energy), Energy used in...",UAZ
11,VUAZ-11,'co2':3 'emiss':2 'energi':4 'fao':1 'fisheri'...,"FAO: Emissions (CO2) (Energy), Fuel oil used ...",UAZ
12,VUAZ-12,'co2':3 'diesel':7 'emiss':2 'energi':4 'fao':...,"FAO: Emissions (CO2) (Energy), Gas-diesel oil...",UAZ
13,VUAZ-13,'agricultur':9 'co2':3 'emiss':2 'energi':4 'e...,"FAO: Emissions (CO2) (Energy), Transport fuel...",UAZ
14,VUAZ-14,"'co2eq':3 'emiss':2 'energi':4,5 'fao':1 'fish...","FAO: Emissions (CO2eq) (Energy), Energy used ...",UAZ
15,VUAZ-15,'co2eq':3 'emiss':2 'energi':4 'fao':1 'fisher...,"FAO: Emissions (CO2eq) (Energy), Fuel oil use...",UAZ
16,VUAZ-16,'co2eq':3 'diesel':7 'emiss':2 'energi':4 'fao...,"FAO: Emissions (CO2eq) (Energy), Gas-diesel o...",UAZ
17,VUAZ-17,'agricultur':9 'co2eq':3 'emiss':2 'energi':4 ...,"FAO: Emissions (CO2eq) (Energy), Transport fu...",UAZ
18,VUAZ-18,"'ch4':5 'co2eq':3 'emiss':2 'energi':6,7 'fao'...","FAO: Emissions (CO2eq) from CH4 (Energy), Ene...",UAZ
19,VUAZ-19,'ch4':5 'co2eq':3 'emiss':2 'energi':6 'fao':1...,"FAO: Emissions (CO2eq) from CH4 (Energy), Fue...",UAZ

**GET `/metadata/variables?admin={keyword}`**

Find variables containing data in a given **admin region**

In [14]:
response = get(f'{datamart_api_url}/metadata/variables?admin=oromia')
df = pd.DataFrame(response.json())
df.head(20)

,variable_id,variable_text,name,dataset_id
0,VUAZ-1,"'bioenergi':2,11 'energi':9 'fao':1 'product':...",FAO: Bioenergy production as a % of total ren...,UAZ
1,VUAZ-9,'agricultur':9 'ch4':3 'emiss':2 'energi':4 'e...,"FAO: Emissions (CH4) (Energy), Transport fuel...",UAZ
2,VUAZ-0,"'agricultur':2,16 'energi':5,11,13 'fao':1 'fo...",FAO: Agriculture and forestry energy use as a...,UAZ
3,VUAZ-2,'agricultur':4 'consumpt':2 'energi':5 'fao':1...,"FAO: Consumption in Agriculture, Energy used ...",UAZ
4,VUAZ-3,'agricultur':4 'consumpt':2 'fao':1 'fisheri':...,"FAO: Consumption in Agriculture, Fuel oil use...",UAZ
5,VUAZ-4,'agricultur':4 'consumpt':2 'diesel':7 'fao':1...,"FAO: Consumption in Agriculture, Gas-diesel o...",UAZ
6,VUAZ-5,"'agricultur':4,9 'consumpt':2 'excl':10 'fao':...","FAO: Consumption in Agriculture, Transport fu...",UAZ
7,VUAZ-6,"'ch4':3 'emiss':2 'energi':4,5 'fao':1 'fisher...","FAO: Emissions (CH4) (Energy), Energy used in...",UAZ
8,VUAZ-7,'ch4':3 'emiss':2 'energi':4 'fao':1 'fisheri'...,"FAO: Emissions (CH4) (Energy), Fuel oil used ...",UAZ
9,VUAZ-8,'ch4':3 'diesel':7 'emiss':2 'energi':4 'fao':...,"FAO: Emissions (CH4) (Energy), Gas-diesel oil...",UAZ
10,VUAZ-10,"'co2':3 'emiss':2 'energi':4,5 'fao':1 'fisher...","FAO: Emissions (CO2) (Energy), Energy used in...",UAZ
11,VUAZ-11,'co2':3 'emiss':2 'energi':4 'fao':1 'fisheri'...,"FAO: Emissions (CO2) (Energy), Fuel oil used ...",UAZ
12,VUAZ-12,'co2':3 'diesel':7 'emiss':2 'energi':4 'fao':...,"FAO: Emissions (CO2) (Energy), Gas-diesel oil...",UAZ
13,VUAZ-13,'agricultur':9 'co2':3 'emiss':2 'energi':4 'e...,"FAO: Emissions (CO2) (Energy), Transport fuel...",UAZ
14,VUAZ-14,"'co2eq':3 'emiss':2 'energi':4,5 'fao':1 'fish...","FAO: Emissions (CO2eq) (Energy), Energy used ...",UAZ
15,VUAZ-15,'co2eq':3 'emiss':2 'energi':4 'fao':1 'fisher...,"FAO: Emissions (CO2eq) (Energy), Fuel oil use...",UAZ
16,VUAZ-16,'co2eq':3 'diesel':7 'emiss':2 'energi':4 'fao...,"FAO: Emissions (CO2eq) (Energy), Gas-diesel o...",UAZ
17,VUAZ-17,'agricultur':9 'co2eq':3 'emiss':2 'energi':4 ...,"FAO: Emissions (CO2eq) (Energy), Transport fu...",UAZ
18,VUAZ-18,"'ch4':5 'co2eq':3 'emiss':2 'energi':6,7 'fao'...","FAO: Emissions (CO2eq) from CH4 (Energy), Ene...",UAZ
19,VUAZ-19,'ch4':5 'co2eq':3 'emiss':2 'energi':6 'fao':1...,"FAO: Emissions (CO2eq) from CH4 (Energy), Fue...",UAZ

### Get time series data for a variable

**GET `/datasets/{dataset_id}/variables/{variable_id}`**

In [15]:
response = get(f'{datamart_api_url}/datasets/WDI/variables/access_to_electricity_of_population')
df = pd.read_csv(StringIO(response.text))
display(HTML(df.fillna('').head(20).to_html(index=False)))

### Get time series data for a variable for a country

**GET `/datasets/{dataset_id}/variables/{variable_id}?country={country}`**

Get data for **Gabon**

In [16]:
response = get(f'{datamart_api_url}/datasets/WDI/variables/access_to_electricity_of_population?country=Gabon')
df = pd.read_csv(StringIO(response.text))
display(HTML(df.fillna('').to_html(index=False)))

Get data for **Gabon OR Guinea**

In [17]:
response = get(f'{datamart_api_url}/datasets/WDI/variables/access_to_electricity_of_population?country=Gabon&country=Guinea')
df = pd.read_csv(StringIO(response.text))
display(HTML(df.fillna('').to_html(index=False)))

### Get time series data for all variables in a dataset

**GET `/datasets/{dataset_id}/variables`**

**Please note that this API will return data for 20 variables only, by default. However that limit can be increased by setting the limit in the url**

For example, to fetch 50 variables,

**GET `/datasets/{dataset_id}/variables?limit=50`**

In [18]:
response = get(f'{datamart_api_url}/datasets/WDI/variables')
df = pd.read_csv(StringIO(response.text), dtype=object)
print(f'Number of rows in the file: {len(df)}')
display(HTML(df.fillna('').head(20).to_html(index=False)))

Number of rows in the file: 29311

### Get time series for multiple variables in a dataset

**GET `/datasets/{dataset_id}/variables?variable={variable_id}`**

Get data for variables **`access_to_clean_fuels_and_technologies_for_cooking_of_population` AND
`access_to_electricity_of_population`**

In [19]:
response = get(f'{datamart_api_url}/datasets/WDI/variables?variable=access_to_clean_fuels_and_technologies_for_cooking_of_population&variable=access_to_electricity_of_population')
df = pd.read_csv(StringIO(response.text))
# display only 30 rows
display(HTML(df.fillna('').head(30).to_html(index=False)))

### Get time series for multiple variables in a dataset, filter by country

**GET `/datasets/{dataset_id}/variables?variable={variable_id}&country={country}`**

Get data for variables 
**`access_to_clean_fuels_and_technologies_for_cooking_of_population` AND
`access_to_electricity_of_population`** 
and country **Gabon**

In [20]:
response = get(f'{datamart_api_url}/datasets/WDI/variables?variable=access_to_clean_fuels_and_technologies_for_cooking_of_population&variable=access_to_electricity_of_population&country=Gabon')
df = pd.read_csv(StringIO(response.text))
display(HTML(df.fillna('').to_html(index=False)))

### Create a new dataset

**NOTE: If the following POST methods have already been ran against the Datamart server, then server will respond with error messages.**

**POST `/metadata/datasets`**

In [21]:
# Define a new dataset
test_dataset = {
    "name": "TEST01",
    "dataset_id": "TEST01",
    "description": "TEST01",
    "url": "http://test01.com/test"
}

In [22]:
# post it to the API
td_response = post(f'{datamart_api_url}/metadata/datasets', json=test_dataset)
print(json.dumps(td_response.json(), indent=2))

{
  "name": "TEST01",
  "description": "TEST01",
  "url": "http://test01.com/test",
  "dataset_id": "TEST01"
}

**NOTE: If the above POST method has already been ran against this Datamart server, then server will respond with:**

```
{
  "Error": "Dataset identifier TEST01 has already been used"
}
```

Retrieve all datasets

In [23]:
response = get(f'{datamart_api_url}/metadata/datasets')
df = pd.DataFrame(response.json())
df

,name,description,url,dataset_id
0,UAZ Indicators,"Collection of indicators, including indicators...",https://github.com/ml4ai/delphi,UAZ
1,WDI dataset,World Development Indicators,https://databank.worldbank.org/source/world-de...,WDI
2,Corruption Perceptions Index,Transparency International Corruption Percept...,https://www.transparency.org/,TICPI
3,SIPRI Military Expenditure,"Military expenditure by country, in millions o...",https://sipri.org/databases/milex,SIPRI
4,economic fitness dataset,EconomicFitness,https://databank.banquemondiale.org/source/eco...,EconomicFitness
5,Agricultural Market Information System (AMIS),The Agricultural Market Information System (AM...,http://www.amis-outlook.org,AMIS
6,test test test,testy test,https://test.com,TEST000
7,World Press Freedom Index,Published every year since 2002 by Reporters W...,https://rsf.org/en,WPFI
8,Poverty Rate Global DP,Poverty Rate Global DP,http://url,DPPoverty
9,FSI dataset,data downloaded from FSI,https://fragilestatesindex.org,FSI
10,OECD dataset,data downloaded from OECD,https://data.oecd.org,OECD
11,WGI dataset,Worldwide Governance Indicators,https://databank.worldbank.org/source/worldwid...,WGI
12,TEST01,TEST01,http://test01.com/test,TEST01

The newly created dataset `TEST01` is returned

### Create a variable in the dataset `TEST01`

**POST `/metadata/datasets/{dataset_id}/variables`**

In [24]:
# define a new variable
test_variable = {
    "name": "test variable for test dataset",
    "variable_id": "TEST01-01"
}

In [25]:
tv_response = post(f'{datamart_api_url}/metadata/datasets/TEST01/variables', json=test_variable)
print(json.dumps(tv_response.json(), indent=2))

{
  "name": "test variable for test dataset",
  "variable_id": "TEST01-01",
  "dataset_id": "TEST01",
  "corresponds_to_property": "PTEST01-TEST01-01"
}

**NOTE: If the above POST method has already been ran against this Datamart server, then server will respond with:**

```
{
  "Error": "Variable TEST01-01 has already been defined in dataset TEST01"
}
```

Retrieve all variables for the dataset `TEST01`

In [26]:
response = get(f'{datamart_api_url}/metadata/datasets/TEST01/variables')
df = pd.DataFrame(response.json())
df

,name,variable_id,description,corresponds_to_property
0,test variable for test dataset,TEST01-01,test variable for test dataset,PTEST01-TEST01-01

The variable `TEST01-01` is created in the dataset `TEST01`

### Upload data to a variable

Lets upload data to the dataset: TEST01 and the variable TEST01-01.

**PUT /datasets/{dataset_id}/variables/{variable_id}**

The upload data API validates the input file.

All required columns are:

- main_subject
- value
- time
- time_precision
- country

We will upload the contents of the file in test_data/test_sample.csv, which is a valid file

In [28]:
df = pd.read_csv('test/test_data/test_sample.csv')
df

,main_subject,value,value_unit,time,time_precision,country,source,dataset_id,variable_id
0,belllgium,1.8,Annual growth %,2019-01-01T00:00:00Z,year,belllgium,OECD,TEST01,TEST01-01
1,bellgium,1.9,Annual growth %,2020-01-01T00:00:00Z,year,bellgium,OECD,TEST01,TEST01-01

In [29]:
url = f'{datamart_api_url}/datasets/TEST01/variables/TEST01-01'
file_path = 'test/test_data/test_sample.csv'
upload_data(file_path, url)

2 rows imported!

In [30]:
response = get(f'{datamart_api_url}/datasets/TEST01/variables/TEST01-01')
df = pd.read_csv(StringIO(response.text))
display(HTML(df.to_html()))

### Upload an Annotated spreadsheet

We can upload an annotated spreadsheet for a dataset as well. Annotation example - https://docs.google.com/spreadsheets/d/1fLEPvEu9OuKa2_7BEzhY0oWGZ_9CMXEE/edit#gid=280610980

**POST `datasets/{dataset_id}/annotated?create_if_not_exist=true`**

  This API call creates a dataset if it does not exist, reads the dataset metadata as follows
       - dataset_id: cell B1
       - name: cell C1
       - description: cell D1
       - url: cell E1
    If any of the above fields are blank, and the dataset does not exist, an error will be returned

In [25]:
annotated_f_path = 'test/test_data/demo_annotated_aid_worker_with_dataset_metadata.xlsx'
df = pd.read_excel(annotated_f_path, header=None).fillna('')
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,dataset,new_dataset_demo,new dataset,new dataset for demo,http://newaid/test,,,,,,,,
1,role,time,time,time,main subject,location,qualifier,variable,qualifier,qualifier,qualifier,location,location
2,type,year,month,day,country,admin1,string,number,string,string,string,latitude,longitude
3,description,,,,,,,,,,,,
4,name,,,,,,,,,,,,
5,unit,,,,,,,person,,,,,
6,header,Year,Month,Day,Country,Region,City,INGO,Means of attack,Attack context,Location,Latitude,Longitude
7,data,1997,9,24,Ethiopia,Ogaden,roadside,0,Shooting,Individual attack,Unknown,8.53056,44.795
8,,1998,6,25,Ethiopia,Somali,travelling from Gode to Degeh Bur,0,Kidnapping,Ambush,Road,7,44
9,,1999,4,1,Ethiopia,,around the corner,1,Kidnapping,Unknown,Unknown,9.145,40.4897

In the above file, the dataset metadata is present in the cells `B1`(1,0), `C1`(2,0), `D1`(3,0) and `E1`(4,0) in the above example.

In [30]:
url = f'{datamart_api_url}/datasets/new_dataset_demo/annotated?create_if_not_exist=true'
file_path = 'test/test_data/demo_annotated_aid_worker_with_dataset_metadata.xlsx'
upload_data_annotated(file_path, url)

[
  {
    "name": "INGO",
    "variable_id": "ingo",
    "dataset_id": "new_dataset_demo",
    "description": "variable column in Qnew_dataset_demo",
    "corresponds_to_property": "PVARIABLE-Qnew_dataset_demo-003",
    "qualifier": [
      {
        "name": "Location",
        "identifier": "PQUALIFIER-Qnew_dataset_demo-006",
        "data_type": "String"
      },
      {
        "name": "Attack context",
        "identifier": "PQUALIFIER-Qnew_dataset_demo-005",
        "data_type": "String"
      },
      {
        "name": "Means of attack",
        "identifier": "PQUALIFIER-Qnew_dataset_demo-004",
        "data_type": "String"
      },
      {
        "name": "City",
        "identifier": "PQUALIFIER-Qnew_dataset_demo-002",
        "data_type": "String"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      },
      {
        "name": "point in time",
        "identifier": "P585"
      }
    ]
  }
]

### Upload an Annotated spreadsheet to a new dataset, creating dataset first

**POST `datasets/{dataset_id}/annotated`**

Lets upload a sample annotated file to the dataset `TEST01`

In [34]:
test_dataset = {
    "name": "TESTAID",
    "dataset_id": "TESTAID",
    "description": "TESTAID",
    "url": "http://testaid.com/test"
}
td_response = post(f'{datamart_api_url}/metadata/datasets', json=test_dataset)
print(json.dumps(td_response.json(), indent=2))

{
  "name": "TESTAID",
  "description": "TESTAID",
  "url": "http://testaid.com/test",
  "dataset_id": "TESTAID"
}

In [35]:
url = f'{datamart_api_url}/datasets/TESTAID/annotated'
file_path = 'test/test_data/demo_annotated_aid_worker.xlsx'
upload_data_annotated(file_path, url)

[
  {
    "name": "INGO",
    "variable_id": "ingo",
    "dataset_id": "TESTAID",
    "description": "variable column in QTESTAID",
    "corresponds_to_property": "PVARIABLE-QTESTAID-003",
    "qualifier": [
      {
        "name": "Location",
        "identifier": "PQUALIFIER-QTESTAID-006",
        "data_type": "String"
      },
      {
        "name": "Attack context",
        "identifier": "PQUALIFIER-QTESTAID-005",
        "data_type": "String"
      },
      {
        "name": "Means of attack",
        "identifier": "PQUALIFIER-QTESTAID-004",
        "data_type": "String"
      },
      {
        "name": "City",
        "identifier": "PQUALIFIER-QTESTAID-002",
        "data_type": "String"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      },
      {
        "name": "point in time",
        "identifier": "P585"
      }
    ]
  }
]

In [36]:
response = get(f'{datamart_api_url}/metadata/datasets/TESTAID/variables')
print(len(response.json()))
print(json.dumps(response.json(), indent=2)) # print only 5 variables

1
[
  {
    "name": "INGO",
    "variable_id": "ingo",
    "description": "variable column in QTESTAID",
    "corresponds_to_property": "PVARIABLE-QTESTAID-003",
    "qualifier": [
      {
        "name": "Location",
        "identifier": "PQUALIFIER-QTESTAID-006",
        "data_type": "String"
      },
      {
        "name": "Attack context",
        "identifier": "PQUALIFIER-QTESTAID-005",
        "data_type": "String"
      },
      {
        "name": "Means of attack",
        "identifier": "PQUALIFIER-QTESTAID-004",
        "data_type": "String"
      },
      {
        "name": "City",
        "identifier": "PQUALIFIER-QTESTAID-002",
        "data_type": "String"
      },
      {
        "name": "stated in",
        "identifier": "P248"
      },
      {
        "name": "point in time",
        "identifier": "P585"
      }
    ]
  }
]

In [37]:
response = get(f'{datamart_api_url}/datasets/TESTAID/variables/ingo')
df = pd.read_csv(StringIO(response.text))
display(HTML(df.fillna('').to_html(index=False)))